verbose: false
instrumentation:
    default-excludes: true
    excludes: ["test/**", "config/**"]
    variable: __coverage__
    compact: true
reporting:
    print: summary
    reports:
        - cobertura
    dir: ./shippable/codecoverage
    map: true
    remap: true
    watermarks:
        statements: [50, 80]
        lines: [50, 80]
        functions: [50, 80]
        branches: [50, 80]